### ISSUE TITLE
Project One Feedback

### ISSUE THREAD

**Issue by ajhofferber** [carolinasno/Project1Game#1]
Hey Carolina,

Nice job with the first project! I really liked your idea to make a trivia game, and the Parks and Rec theme is super fun.  It looks like you were able to work out scoring logic after all... nice!  

Your scripts code is broken out well and the comments that you added really help me to understand what is going on in each part of your code.  As you continue, maybe think about how you are using indentation and white space.  Also, good start on your readme!  Here is this: https://help.github.com/articles/markdown-basics/ some markdown documentation to maybe help you get your pictures inserted properly, as well as have your link actually link to your project.

Good stuff!

-Ash

**Comment by Avizacherman** [comment]
Carolina,

Great to see you got it all working. Perhaps now it's time to Treat Yo Self! Really good work and a fun time all around.

I like the organization of your code and I'm glad to see you were able to separate DOM from logic like we discussed. The site itself looks great and is really clean. 

Score: 2 (see Rubric for socring details).

-Avi
